version: "3.9"

services:
  mysql:
    image: "mysql:8.0.29"
    container_name: "${CONTAINER_NAME}"
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - "musicbot-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

volumes:
  musicbot-data: