spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    username: musicbot
    password: musicbot
    url: jdbc:mysql://localhost:4500/musicbot

  jpa:
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          discord:
            client-id:
            client-secret:
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope:
              - identify
              - guilds
            redirect-uri: "{baseUrl}/login/oauth2/code/discord"

        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username
